version: 0.0
os: linux

files:
  - source: target/*.war
    destination: /opt/tomcat/webapps/

hooks:
  BeforeInstall:
    - location: scripts/before.sh
    - timeout: 100
    - runas: root
  AfterInstall:
    - location: scripts/after.sh
    - timeout: 100
    - runas: root
